name: Tests

on:
  - push
  - pull_request

jobs:
  run-tests:
    strategy:
      matrix:
        include:
          - name: Windows Tests
            os: windows-latest
            architecture: x64
          - name: MacOS x64 Tests
            os: macos-15-intel
            architecture: x64
          - name: MacOS arm64 Tests
            os: macos-latest
            architecture: arm64
          - name: Linux Tests
            os: ubuntu-latest
            architecture: x64

    runs-on: ${{ matrix.os }}
    environment: ${{ github.event.inputs.env || 'Development' }}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        id: setup-py
        uses: actions/setup-python@v6
        with:
          # TODO: Unfreeze python version when this is resolved: https://github.com/actions/setup-python/issues/886
          python-version: "3.12"
          check-latest: true
          cache: "pip" # Cache all pip dependency downloads
      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: ${{ matrix.os }}-tests-venv-${{ steps.setup-py.outputs.python-version }}-${{ hashFiles('**/req*.txt') }}
      - name: Create venv
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv ./.venv
      - name: Activate venv
        run: |
          source ./.venv/bin/activate || source ./.venv/Scripts/activate
          echo $PATH >> $GITHUB_PATH
      - name: Install venv dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          python -m pip install -r requirements.txt

      - name: Test python formatting
        run: black . --check

      - name: Run tests
        run: |
          pytest -n auto
